- name: add EPEL repository
  yum_repository:
    name: epel
    description: YUM repository for EPEL
    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/
    gpgcheck: no

- name: create .ssh directory for vagrant@postgres
  file:
      path: '/home/vagrant/.ssh'
      owner: vagrant
      group: vagrant
      state: directory
      mode: "u+rw,g-rwx,o-rwx"

- name: add Jenkins public key to vagrants authorized_keys
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', 'authorized_keys') }}"
