- name: add jenkins repository
  yum_repository:
    name: jenkins
    description: YUM repository for Jenkins
    baseurl: http://pkg.jenkins.io/redhat
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: install java dependency
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: install jenkins server
  yum:
    name: jenkins
    state: latest

- name: activate and start jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes