- name: create .ssh directory for Jenkins
  file:
      path: '/var/lib/jenkins/.ssh'
      owner: jenkins
      group: jenkins
      state: directory
      mode: "u+rw,g-rwx,o-rwx"

- name: copy keys in to .ssh directory
  copy:
      src: '{{ item }}'
      dest: '/var/lib/jenkins/.ssh/'
      owner: jenkins
      group: jenkins
      mode: "u+rw,g-rwx,o-rwx"
  with_items:
  - id_rsa
  - id_rsa.pub

- name: add jenkins repository
  yum_repository:
    name: jenkins
    description: YUM repository for Jenkins
    baseurl: http://pkg.jenkins.io/redhat
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: install java dependency
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: install git
  yum:
    name: git
    state: latest

- name: install ansible
  yum:
    name: ansible
    state: latest

- name: install jenkins server
  yum:
    name: jenkins
    state: latest

- name: activate and start jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
