- name: create .ssh directory for vagrant@postgres
  file:
      path: '/home/vagrant/.ssh'
      owner: vagrant
      group: vagrant
      state: directory
      mode: "u+rw,g-rwx,o-rwx"

- name: add Jenkins public key to vagrants authorized_keys
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', 'authorized_keys') }}"

- name: install postgresql
  yum:
    name: postgresql-server
    state: latest

- name: install python-psycopg2 as dependency for ansible
  yum:
    name: python-psycopg2
    state: latest

- name: execute initdb as postgres user
  shell: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/

- name: copy postgres configuration to its destination
  copy:
    src: postgresql.conf
    dest: /var/lib/pgsql/data
    owner: postgres
    group: postgres
    mode: "u=rw,g=r,o=r"

- name: copy access rules to its destination
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/data
    owner: postgres
    group: postgres
    mode: "u=rw,g=r,o=r"

- name: activate and start postgresql
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: create foobar table
  postgresql_db:
    name: foobar

- name: create user django
  postgresql_user:
    db: foobar
    name: django
    password: secret2345
    priv: "ALL"

